/* tslint:disable */
/* eslint-disable */
/**
 * esa API v1
 * チームのナレッジ共有サービス[esa.io](https://esa.io/)のAPI v1の仕様書
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { WatcherUser } from "./watcher-user";

/**
 * 記事をWatchしているユーザーを表します。
 * @export
 * @interface Watcher
 */
export interface Watcher {
  /**
   * Watchをした日時です。
   * @type {string}
   * @memberof Watcher
   */
  created_at: string;
  /**
   *
   * @type {WatcherUser}
   * @memberof Watcher
   */
  user: WatcherUser;
}
